//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Logout_Form.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {

        public int ID { get; set; }

        [Required(ErrorMessage ="UserName is Required!!")]
        [StringLength(50, MinimumLength = 3)]
        [DisplayName("User Name")]
        public string Username { get; set; }

        [Required(ErrorMessage ="Password field is also required to login!!")]
        [DataType(DataType.Password)]
        [StringLength (15, MinimumLength = 4, ErrorMessage ="You Entered Wrong Password or Character limit is min or max!!")]
        [DisplayName("User Password")]
        public string Password { get; set; }

        [DisplayName("Remember me")]
        public bool Rememberme { get; set; }
    }
}
